export default [
  {
    path: "/component/curd",
    // component: "demo/curd/index",
    component: () => import("@/views/demo/curd/index"),
    name: "Curd",
    meta: {
      title: "增删改查",
      icon: "",
      hidden: false,
      keepAlive: true,
      alwaysShow: false,
      params: null,
    },
  },
  {
    path: "/component/table-select",
    component: () => import("@/views/demo/table-select/index"),
    name: "TableSelect",
    meta: {
      title: "列表选择器",
      icon: "",
      hidden: false,
      keepAlive: true,
      alwaysShow: false,
      params: null,
    },
  },
  {
    path: "/component/wang-editor",
    component: () => import("@/views/demo/wang-editor"),
    name: "WangEditor",
    meta: {
      title: "富文本编辑器",
      icon: "",
      hidden: false,
      keepAlive: true,
      alwaysShow: false,
      params: null,
    },
  },
  {
    path: "/component/upload",
    component: () => import("@/views/demo/upload"),
    name: "Upload",
    meta: {
      title: "图片上传",
      icon: "",
      hidden: false,
      keepAlive: true,
      alwaysShow: false,
      params: null,
    },
  },
  {
    path: "/component/dict-demo",
    component: () => import("@/views/demo/dictionary"),
    name: "DictDemo",
    meta: {
      title: "字典组件",
      icon: "",
      hidden: false,
      keepAlive: true,
      alwaysShow: false,
      params: null,
    },
  },
  {
    path: "/component/icon-selector",
    component: () => import("@/views/demo/icon-selector"),
    name: "IconSelector",
    meta: {
      title: "图标选择器",
      icon: "",
      hidden: false,
      keepAlive: true,
      alwaysShow: false,
      params: null,
    },
  },
];
