export default [
  {
    path: "/system/user",
    component: () => import("@/views/system/user/index"),
    name: "User",
    meta: {
      title: "用户管理",
      icon: "el-icon-User",
      hidden: false,
      keepAlive: true,
      alwaysShow: false,
      params: null,
    },
  },
  {
    path: "/system/role",
    component: () => import("@/views/system/role/index"),
    name: "Role",
    meta: {
      title: "角色管理",
      icon: "role",
      hidden: false,
      keepAlive: true,
      alwaysShow: false,
      params: null,
    },
  },
  {
    path: "/system/menu",
    component: () => import("@/views/system/menu/index"),
    name: "SysMenu",
    meta: {
      title: "菜单管理",
      icon: "menu",
      hidden: false,
      keepAlive: true,
      alwaysShow: false,
      params: null,
    },
  },
  {
    path: "/system/dept",
    component: () => import("@/views/system/dept/index"),
    name: "Dept",
    meta: {
      title: "部门管理",
      icon: "tree",
      hidden: false,
      keepAlive: true,
      alwaysShow: false,
      params: null,
    },
  },
  {
    path: "/system/dict",
    component: () => import("@/views/system/dict/index"),
    name: "Dict",
    meta: {
      title: "字典管理",
      icon: "dict",
      hidden: false,
      keepAlive: true,
      alwaysShow: false,
      params: null,
    },
  },
  {
    path: "/system/log",
    component: () => import("@/views/system/log/index"),
    name: "Log",
    meta: {
      title: "系统日志",
      icon: "document",
      hidden: false,
      keepAlive: true,
      alwaysShow: false,
      params: null,
    },
  },
  {
    path: "/system/dict-data",
    component: () => import("@/views/system/dict/data"),
    name: "DictData",
    meta: {
      title: "字典数据",
      icon: "",
      hidden: true,
      hiddenLayout: false,
      keepAlive: true,
      alwaysShow: false,
      params: null,
    },
  },
];
